<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddMedicineInventorySeeder extends Seeder
{
    public function run(): void
    {
        $medicines = [
            [
                'name' => 'Paracetamol 500mg',
                'generic_name' => 'Paracetamol',
                'brand_name' => 'Paracetamol Plus',
                'description' => 'Pain reliever and fever reducer',
                'category' => 'Analgesic',
                'unit' => 'tablet',
                'quantity' => 1000,
                'reorder_level' => 100,
                'unit_price' => 5.50,
                'selling_price' => 7.25,
                'expiry_date' => '2025-12-31',
                'batch_number' => 'PARA2024001',
                'supplier_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Amoxicillin 500mg',
                'generic_name' => 'Amoxicillin',
                'brand_name' => 'Amoxil',
                'description' => 'Antibiotic for bacterial infections',
                'category' => 'Antibiotic',
                'unit' => 'capsule',
                'quantity' => 500,
                'reorder_level' => 50,
                'unit_price' => 12.75,
                'selling_price' => 15.99,
                'expiry_date' => '2025-11-30',
                'batch_number' => 'AMOX2024001',
                'supplier_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ibuprofen 400mg',
                'generic_name' => 'Ibuprofen',
                'brand_name' => 'Advil',
                'description' => 'Anti-inflammatory pain medication',
                'category' => 'NSAID',
                'unit' => 'tablet',
                'quantity' => 750,
                'reorder_level' => 75,
                'unit_price' => 8.25,
                'selling_price' => 10.50,
                'expiry_date' => '2026-01-15',
                'batch_number' => 'IBU2024001',
                'supplier_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Omeprazole 20mg',
                'generic_name' => 'Omeprazole',
                'brand_name' => 'Prilosec',
                'description' => 'Proton pump inhibitor for acid reflux',
                'category' => 'PPI',
                'unit' => 'capsule',
                'quantity' => 300,
                'reorder_level' => 30,
                'unit_price' => 15.99,
                'selling_price' => 19.99,
                'expiry_date' => '2025-10-31',
                'batch_number' => 'OME2024001',
                'supplier_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Metformin 500mg',
                'generic_name' => 'Metformin',
                'brand_name' => 'Glucophage',
                'description' => 'Oral diabetes medication',
                'category' => 'Antidiabetic',
                'unit' => 'tablet',
                'quantity' => 600,
                'reorder_level' => 60,
                'unit_price' => 7.50,
                'selling_price' => 9.99,
                'expiry_date' => '2026-02-28',
                'batch_number' => 'MET2024001',
                'supplier_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lisinopril 10mg',
                'generic_name' => 'Lisinopril',
                'brand_name' => 'Zestril',
                'description' => 'ACE inhibitor for blood pressure',
                'category' => 'Antihypertensive',
                'unit' => 'tablet',
                'quantity' => 400,
                'reorder_level' => 40,
                'unit_price' => 9.99,
                'selling_price' => 12.50,
                'expiry_date' => '2025-12-15',
                'batch_number' => 'LIS2024001',
                'supplier_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Simvastatin 20mg',
                'generic_name' => 'Simvastatin',
                'brand_name' => 'Zocor',
                'description' => 'Statin for cholesterol management',
                'category' => 'Lipid Lowering',
                'unit' => 'tablet',
                'quantity' => 350,
                'reorder_level' => 35,
                'unit_price' => 18.75,
                'selling_price' => 22.99,
                'expiry_date' => '2025-11-15',
                'batch_number' => 'SIM2024001',
                'supplier_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cetirizine 10mg',
                'generic_name' => 'Cetirizine',
                'brand_name' => 'Zyrtec',
                'description' => 'Antihistamine for allergies',
                'category' => 'Antihistamine',
                'unit' => 'tablet',
                'quantity' => 800,
                'reorder_level' => 80,
                'unit_price' => 4.25,
                'selling_price' => 6.99,
                'expiry_date' => '2026-03-31',
                'batch_number' => 'CET2024001',
                'supplier_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($medicines as $medicine) {
            DB::table('inventory_items')->updateOrInsert(
                ['name' => $medicine['name']],
                $medicine
            );
        }

        $this->command->info('Added 8 medicines to inventory for prescription testing');
    }
}
